### ISSUE TITLE
Navbar's 'Product' dropdown overflows and has horizontal scroll bar

### ISSUE THREAD

**Issue by willhamilton24** [SetProtocol/index-ui#146]

**Comment by willhamilton24** [comment]
@0xModene Still isn't

<img width="392" alt="Screen Shot 2021-04-05 at 9 37 20 PM" src="https://user-images.githubusercontent.com/23125216/113646674-493d3000-9657-11eb-95fe-5387ca0a468b.png">
t

**Comment by 0xModene** [comment]
@willhamilton24 Hey Will, want to double check the site now and let me know if its gone for you?

**Comment by 0xModene** [comment]
I'm going to close this now, since its been resolved and pushed to prod
