### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by franklili3** [SetProtocol/index-ui#186]
I have clone this repo, run `npm install`, and `yarn start`, there is error, 

> Failed to compile
./src/hooks/useLocalStorage.ts
  Line 0:  Parsing error: Cannot read property 'map' of undefined

> 
How can I do?
OS:ubuntu 20

**Comment by 0xModene** [comment]
hey @franklili3 did also perform this step?

`cp .env.prod .env`

**Comment by franklili3** [comment]
Yes, I have run `cp .env.prod .env`, but I have not changed .env file.

**Comment by franklili3** [comment]
I got the reason. I should run `yarn install` before `yarn start`. Please add this in Readme.

**Comment by 0xModene** [comment]
Thanks for that note. I'll get that added!
