### ISSUE TITLE
Vote page upgrades

### ISSUE THREAD

**Issue by 0xModene** [SetProtocol/index-ui#189]
Some things can be added to the /vote page, and probably need some input from the design team

1. Indicate vote pass/fail
2. Indicate quorum
3. Indicate voting deadline

How do we consider Boardroom vs Snapshot? What does governance look like for us going forward?

**Comment by DevOnDeFi** [comment]
I suggest you devs make these changes now, using layout in a table as you will, then we will put a UX designer on this page as part of larger site build. Dont want to delay y'all here - it would help users to have this info in next few weeks/couple months.

As long as @controtie @0xModene don't mind the resource usage like this. Your cost to weigh

**Comment by 0xModene** [comment]
Thanks guys, appreciate the input
