### ISSUE TITLE
Create Contribution Guidelines

### ISSUE THREAD

**Issue by 0xModene** [SetProtocol/index-ui#208]
The index-ui repo needs contribution guidelines to make things easier for newcomers trying to get the lay of the land.

- Create a `CONTRIBUTING.md` file at project root
- Populate that file with something akin to [this](https://github.com/emilk/egui/blob/master/CONTRIBUTING.md)

The contents of this probably should be discussed in `#dev` channel on the Discord, as our needs will inevitably be different than other repos.

**Comment by 0xModene** [comment]
https://mozilla.github.io/open-leadership-training-series/articles/building-communities-of-contributors/write-contributor-guidelines/

**Comment by tytarman** [comment]
I can get this done for you

**Comment by 0xModene** [comment]
Go for it

**Comment by 0xModene** [comment]
Closed by #232
