### ISSUE TITLE
Buy/Sell widget needs better padding

### ISSUE THREAD

**Issue by 0xModene** [SetProtocol/index-ui#238]
**Describe the bug**
The Buy/Sell widget has some broke padding when trying to select token, and it seems to cut off the last couple pixels of each token in the list

**To Reproduce**
1. Go to http://indexcoop.com/dpi
2. View Buy/Sell widget, should see something like the below screenshot

**Expected behavior**
This should not cut the letters off prematurely

**Screenshots**
![image](https://user-images.githubusercontent.com/7647623/118718201-f9748b80-b7f4-11eb-9369-0270c8ea31f7.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Brave

**Comment by DuanLeeWatkins** [comment]
Hello, I would like to solve this issue.

**Comment by 0xModene** [comment]
Have at it

**Comment by JulianAR97** [comment]
I have this done, can I submit a pull request?

**Comment by 0xModene** [comment]
yes
