### ISSUE TITLE
Link to Contribution Guidelines on README

### ISSUE THREAD

**Issue by 0xModene** [SetProtocol/index-ui#248]
**Is your feature request related to a problem? Please describe.**
The README Contributing section should link to CONTRIBUTING.md

**Describe the solution you'd like**
Link to https://github.com/SetProtocol/index-ui/blob/master/CONTRIBUTING.md#-troubleshooting

**Comment by tytarman** [comment]
I'll take care of it. Was gonna ask if we should do that anyway.

**Comment by 0xModene** [comment]
have at it
