### ISSUE TITLE
Update Chart Y Axis Markers

### ISSUE THREAD

**Issue by 0xModene** [SetProtocol/index-ui#267]
**Is your feature request related to a problem? Please describe.**
The YAxis component's min/max labels aren't clear, which can be problematic since the numbers are so close to the price. 

**Describe the solution you'd like**
The YAxis should prepend the current values with High and Low, respectively. 

**Describe alternatives you've considered**
If you have a better idea to indicate to the user that these represent the Y Axis range (ie. making the chart itself more distinguishable as well), then go ahead and try that.

**Additional context**
![image](https://user-images.githubusercontent.com/7647623/119177114-77bd7180-ba31-11eb-8dd1-1807f61a3171.png)

**Comment by tytarman** [comment]
I'll play around with it and see what I can come up with for a solution
