### ISSUE TITLE
View Balance - Wallet Bug

### ISSUE THREAD

**Issue by tytarman** [SetProtocol/index-ui#280]
**Describe the bug**
Viewing Wallet Balance on a Mac laptop does not allow the ability to scroll through balances. Scroll is unresponsive. Additionally, the wallet is opening the bottom of the balances page, rather than the top of the wallet balances.

**To Reproduce**
1. Go to the Index [website](https://www.indexcoop.com/).
2. Click on 'View Balances' in the top right corner.
3. Attempt to scroll...

**Expected behavior**
The popup window should open with the ability to scroll through balances seamlessly, but it should also open at the top of the scrollable window (not the bottom).

**Screenshots**
![view-balances-bug](https://user-images.githubusercontent.com/83655654/120330533-84a05780-c2b2-11eb-9cfc-411eb70335ae.png)

**Desktop (please complete the following information):**
 - OS: [OSX 10.13.6]
 - Browser [Brave]

**Smartphone (please complete the following information):**
 - Version [1.24.86 Chromium: 90.0.4430.212 (Official Build) (x86_64)]

**Additional context**
Problem does not appear to be present on Android or iPhone. I have not tested Windows at this time but will update accordingly once test has been ran.

**Comment by 0xModene** [comment]
Looked at Windows, not an issue here. I do want to note I have a larger monitor, so unsure whether or not this is an issue with resolution. Developer console shows 951px vh

![image](https://user-images.githubusercontent.com/7647623/120334380-33926280-c2b6-11eb-9c5c-a0b71cce502e.png)

**Comment by tytarman** [comment]
Hmm...could just be exclusive to this dinosaur of a laptop that I have, so I'll look into it more and see what I find

**Comment by 0xModene** [comment]
This should be adaptive based on the view height. Some things may be fixed values when they really need to be percentages. Try adjusting the height of those components to be vh or vw, not px vals

**Comment by tytarman** [comment]
@0xModene I tried tweaking things here and there to see what the issue might be, but it turned out to just be a simple cookie issue. Now that I feel dumb, we can close this issue and take note that a rogue cookie can make the wallet bug out on special occasions

**Comment by 0xModene** [comment]
lgtm, will close
