### ISSUE TITLE
FLI rebalancing equations incorrect

### ISSUE THREAD

**Issue by ncitron** [SetProtocol/index-ui#297]
**Describe the bug**

**To Reproduce**
1. Go to https://www.indexcoop.com/ethfli or https://www.indexcoop.com/btcfli
3. Scroll down to the bottom equation
3. See that the equation says ```CLRt+1 = max(MINLR, min(MAXLR, TLR * (1 — RS) + CLRt * RS))``` (this is wrong)

**Expected behavior**
Equation for calculating the new leverage ratio should be:
```CLRt+1 = max(MINLR, min(MAXLR, CLRt * (1 - RS) + TLR * RS))```

**Comment by tytarman** [comment]
I can fix this today. I'll have a PR out for it later
