### ISSUE TITLE
Clean Up Build Warnings

### ISSUE THREAD

**Issue by 0xModene** [SetProtocol/index-ui#307]
The repo has a couple of build warnings that are pretty trivial to remedy

The browser list needs updating, which can be done by running 
`npx browserslist --update-db`

When running `yarn start` to serve the website locally, the following warnings can be found:
<img width="636" alt="Screen Shot 2021-07-11 at 9 54 31 PM" src="https://user-images.githubusercontent.com/7647623/125219437-baadff80-e292-11eb-9954-d06104da6e3b.png">

If after resolving all the above warnings there are a few new ones, those also need to be resolved.

**Comment by tytarman** [comment]
I can also work on this if no one is already in the process. Those warnings have been annoying lately anyway 😂
