### ISSUE TITLE
Incorrect farm dates

### ISSUE THREAD

**Issue by ncitron** [SetProtocol/index-ui#309]
Under https://www.indexcoop.com/liquidity-mining, the DPI and MVI farm show the incorrect dates. These dates should both be updated to be July 13th - August 12th.

Here is a screenshot of the incorrect dates:

<img width="819" alt="Screen Shot 2021-07-14 at 8 57 13 PM" src="https://user-images.githubusercontent.com/16858330/125711375-212712c3-adbe-443b-af60-9680511bbdc0.png">

**Comment by tytarman** [comment]
I'll update them for you

**Comment by ripples3** [comment]
I DMed tyrarman on discord and he said I can do this if I want to.
- Don | ETH to 10k
