### ISSUE TITLE
Update the partners on the homepage

### ISSUE THREAD

**Issue by 0xModene** [SetProtocol/index-ui#311]
**Is your feature request related to a problem? Please describe.**
Sushiswap does not appear on our homepage under the 'Earn Yield' section, even though we have pools in the Onsen. Since making that page, Sushi has also added Kashi, so we can show users they can leverage DPI

**Describe the solution you'd like**
'Lend and Borrow' section: 
- Move 'Lend and Borrow' section to a new row under Wallets section
- Add Sushiswap to the section after CREAM: 
  - copy: Earn yield on DPI by supplying to CREAM Finance
  - link text: Lend on SushiSwap
  - url: https://app.sushi.com/lend

'Earn Yield' sectopm
- Add Sushiswap:
  - copy: Earn yield and Lend your DPI on SushiSwap
  - link text: Farm on SushiSwap
  - url: https://app.sushi.com/farm

Also be sure to make 'Call & Put Options' and 'Smart Contract Covers' mimic the styling of 'Exchanges' in regards to stretching the two remaining items to fill the space. The same should apply for the relocated 'Lend and Borrom'

**Additional context**
We seem to be missing an image for Opyn as they've changed their logo. Perhaps use [this one](https://www.opyn.co/nextimg/%2Fpb_opyn_logo_with_athena2.png/128/75?url=%2Fpb_opyn_logo_with_athena2.png&w=128&q=75)? 
![image](https://user-images.githubusercontent.com/7647623/125816836-a41de9c2-ef6c-4591-bcaa-7d708c9d28d0.png)

**Comment by tytarman** [comment]
Thanks for the details. I'll get to work on it

**Comment by tytarman** [comment]
@0xModene shouldn't this be closed now?

**Comment by 0xModene** [comment]
yup
