### ISSUE TITLE
Remove April MVI farm popup

### ISSUE THREAD

**Issue by ncitron** [SetProtocol/index-ui#314]
On https://www.indexcoop.com/liquidity-mining, there is a box that informs users about the MVI rewards starting on April 8th. This can probably be removed now.

Picture of what needs to be removed for reference:

<img width="840" alt="Screen Shot 2021-07-16 at 12 03 39 AM" src="https://user-images.githubusercontent.com/16858330/125889969-d6d0d927-51a4-4a32-91aa-9832260c2570.png">

**Comment by tytarman** [comment]
I'll remove it for you. Do we want to keep the `import MigrationNotice` command in the code for future use of the banner but with different text? Or remove it completely for now?

**Comment by 0xModene** [comment]
Remove the import if it's no longer being used
