### ISSUE TITLE
BED product page shows market cap of $0

### ISSUE THREAD

**Issue by ncitron** [SetProtocol/index-ui#324]
**Describe the bug**
Market cap data not being fetched/displayed correctly

**To Reproduce**
1. Go to https://www.indexcoop.com/bed 
2. See that the market cap is $0

**Expected behavior**
Should show actual market cap of the product 

**Screenshots**
![Screenshot_2021-07-22_15-12-59](https://user-images.githubusercontent.com/16858330/126696373-99d55a9d-1da4-4931-9046-519fd630e99e.png)

**Comment by ncitron** [comment]
This is probably because the market cap data on CoinGecko is wrong. Might just be worth waiting for CoinGecko to fix it rather than putting in the effort of writing a workaround

**Comment by tytarman** [comment]
I'll fix this for you

**Comment by controtie** [comment]
This has been resolved by Coingecko
