### ISSUE TITLE
Add connect to rainbow button

### ISSUE THREAD

**Issue by ncitron** [SetProtocol/index-ui#342]
**Describe the solution you'd like**
Add a new wallet option in the wallet select model for the Rainbow wallet. When the button is clicked just use WalletConnect.
Some inspiration for how to style it:
https://christianbaroni.github.io/rainbow-buttons
https://github.com/rainbow-me/rainbow-button

**Additional context**
Mike Demarais from https://rainbow.me requested this feature. They've been a huge supporter of the coop and show the DPI prominently on the dashboard of their wallet.
Rainbow wallet connects via WalletConnect. They've been trying to get dapps to create a special "connect to rainbow" button which is just WalletConnect under the hood with their logo slapped on it.

**Comment by ripples3** [comment]
I would like to take this.

Discord name: Don | ETH to 10k#3452
