### ISSUE TITLE
Update MVI LM dates

### ISSUE THREAD

**Issue by 0xModene** [SetProtocol/index-ui#344]
Update MVI LM Dates to the most recent dates

**Comment by ripples3** [comment]
grabbing this ticket.
Index emissions for Aug
https://gov.indexcoop.com/t/iip-63-mvi-liquidity-mining-august-2021/2183

**Comment by ripples3** [comment]
Should we leave DPI as is?
![image](https://user-images.githubusercontent.com/45053256/129481127-db695fc8-d21f-482c-b814-e3d9471c9ec3.png)

**Comment by ripples3** [comment]
Review Mvi farm #346
