### ISSUE TITLE
WalletConnect No Longer Working

### ISSUE THREAD

**Issue by 0xModene** [SetProtocol/index-ui#351]
**Describe the bug**
WalletConnect no longer seems to be working on our website

**To Reproduce**
1. Click 'Unlock Wallet'
![image](https://user-images.githubusercontent.com/7647623/129767217-054c3f62-887a-41c3-aacb-3429c42d535e.png)

2. Select WalletConnect 
![image](https://user-images.githubusercontent.com/7647623/129768449-affd3716-0cb8-4e4e-b2fb-9544d756be40.png)

3. See Error

**Expected behavior**
This should properly connect to the dapp via WalletConnect

**Comment by Boda805** [comment]
@0xModene I'll take an attempt at this.

**Comment by Boda805** [comment]
This can be closed, worked with dylan and he deployed the last PR, and WC is now working on the site.
