### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by jacobabiola** [SetProtocol/index-ui#95]
I have been trying  to resolve this error

`C:/Users/user/index-ui/src/components/BuySell/components/TokenInputs.tsx
TypeScript error in C:/Users/user/index-ui/src/components/BuySell/components/TokenInputs.tsx(25,28):
Expected 1 arguments, but got 0.  TS2554

    23 |   } = useBuySell()
    24 | 
    25 |   const currencyInputRef = useRef<any>()
         |                            ^
    26 |   const setTokenInputRef = useRef<any>()
    27 | 
    28 |   const theme = useTheme()`

**Comment by 0xModene** [comment]
@jacobabiola I don't think this is an issue any longer. Do you want to check on this and verify?

**Comment by 0xModene** [comment]
Hey @jacobabiola , could this be related to #186 ? Check that Issue for a possible resolution.
